# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b9a574e363746f03c9e1f50e0f9bb0c6280a5d0107ccb7a3e8935eb19860cc68c123b7d0c55811fd053d065f65a6682eff4eca38aff78fccc4f5fb79e054cbd

test:
  secret_key_base: 64ac5babd28a1316db4f5b4ca76887c431b6ff6f00d717c64479c836401b977eefd05b3becce2fffb309991b9cc03459af9c4d00dbc3a01e6af4f18d63b33802

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
